quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=short
quarkus.datasource.password=password

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/spotify_copy
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true
